import type { ComplianceMap } from './types';

export const DEMO_PROFILE = {
  businessName: 'The Brewed Awakening',
  ownerName: 'Sarah',
  businessType: 'cafe_restaurant' as const,
  companyType: 'limited' as const,
  councilArea: 'edinburgh' as const,
  postcode: 'EH1 2QL',
  vatRegistered: true,
  vatQuarterEnd: 'march' as const,
  turnoverBand: '85k_250k' as const,
  employeeCount: 4,
  servesAlcohol: true,
  hasOutdoorSeating: true,
  handlesPersonalData: true,
  incorporationDate: '2022-06-15',
  licenceGrantDate: '2022-08-01',
  financialYearEnd: '2026-03-31',
  onboardingComplete: true,
};

export const FALLBACK_COMPLIANCE_MAP: ComplianceMap = {
  profile: DEMO_PROFILE,
  summary:
    'The Brewed Awakening has 14 active compliance obligations across HMRC, Companies House, Food Standards Scotland, the Scottish Licensing Act, employment law, and data protection. 3 items require urgent attention within the next 30 days.',
  riskScore: 62,
  obligations: [
    {
      id: 'fss-hygiene',
      title: 'Food Hygiene Registration',
      category: 'food_safety',
      description: 'Must be registered with City of Edinburgh Council environmental health. Maintain Safer Food Better Business records at all times.',
      appliesWhen: 'All food businesses',
      frequency: 'Ongoing',
      penalty: 'Closure notice, prosecution, or food hygiene improvement notice',
      source: 'Food Standards Scotland',
      sourceUrl: 'https://www.foodstandards.gov.scot/business-and-industry/safety-and-regulation/food-hygiene',
    },
    {
      id: 'fss-allergens',
      title: 'Allergen Information Display (Natasha\'s Law)',
      category: 'food_safety',
      description: 'Full allergen labelling required on all pre-packed for direct sale (PPDS) food. 14 major allergens must be declared. Written allergen information for non-prepacked food.',
      appliesWhen: 'All food businesses',
      frequency: 'Ongoing',
      penalty: 'Unlimited fine and/or up to 2 years imprisonment',
      source: 'Food Standards Scotland',
      sourceUrl: 'https://www.foodstandards.gov.scot/business-and-industry/safety-and-regulation/allergen-information',
    },
    {
      id: 'fss-haccp',
      title: 'Food Safety Management System (HACCP)',
      category: 'food_safety',
      description: 'Must implement and maintain a documented food safety management system based on HACCP principles.',
      appliesWhen: 'All food businesses',
      frequency: 'Ongoing',
      penalty: 'Improvement notice, prohibition order, or prosecution',
      source: 'Food Standards Scotland',
    },
    {
      id: 'hmrc-vat',
      title: 'VAT Returns',
      category: 'hmrc',
      description: 'Submit quarterly VAT return and payment to HMRC.',
      appliesWhen: 'VAT registered (turnover > £85,000)',
      frequency: 'Quarterly',
      penalty: '2% surcharge on VAT owed, escalating to 15%',
      source: 'HMRC',
      sourceUrl: 'https://www.gov.uk/vat-returns',
    },
    {
      id: 'hmrc-paye',
      title: 'PAYE / RTI Submission',
      category: 'hmrc',
      description: 'Report payroll information to HMRC on or before each payday.',
      appliesWhen: 'Has employees (4 employees)',
      frequency: 'Monthly',
      penalty: '£100-£400/month late filing penalty',
      source: 'HMRC',
      sourceUrl: 'https://www.gov.uk/running-payroll',
    },
    {
      id: 'hmrc-corp-tax',
      title: 'Corporation Tax',
      category: 'hmrc',
      description: 'Pay Corporation Tax 9 months + 1 day after accounting period end. File return within 12 months.',
      appliesWhen: 'Limited company',
      frequency: 'Annual',
      penalty: '£100 penalty, then £200 after 3 months',
      source: 'HMRC',
      sourceUrl: 'https://www.gov.uk/corporation-tax',
    },
    {
      id: 'ch-confirmation',
      title: 'Companies House Confirmation Statement',
      category: 'companies_house',
      description: 'Annual confirmation that company details are up to date.',
      appliesWhen: 'Limited company',
      frequency: 'Annual',
      penalty: '£150 initial penalty, escalating to £1,500',
      source: 'Companies House',
      sourceUrl: 'https://www.gov.uk/confirmation-statement',
    },
    {
      id: 'ch-accounts',
      title: 'Annual Accounts Filing',
      category: 'companies_house',
      description: 'File annual accounts within 9 months of financial year end.',
      appliesWhen: 'Limited company',
      frequency: 'Annual',
      penalty: '£150 escalating to £1,500',
      source: 'Companies House',
      sourceUrl: 'https://www.gov.uk/file-your-company-annual-accounts',
    },
    {
      id: 'licence-premises',
      title: 'Premises Licence Annual Fee',
      category: 'scottish',
      description: 'Annual fee to City of Edinburgh Council licensing board under the Scottish Licensing Act 2005.',
      appliesWhen: 'Serves alcohol',
      frequency: 'Annual',
      penalty: 'Licence suspension or revocation',
      source: 'City of Edinburgh Council / Scottish Licensing Act 2005',
    },
    {
      id: 'licence-personal',
      title: 'Personal Licence Holder Training',
      category: 'scottish',
      description: 'Scottish Certificate for Personal Licence Holders. Mandatory training refresher every 5 years.',
      appliesWhen: 'Serves alcohol',
      frequency: 'Every 5 years',
      penalty: 'Loss of personal licence',
      source: 'Scottish Licensing Act 2005',
    },
    {
      id: 'council-outdoor',
      title: 'Outdoor Seating Licence',
      category: 'council',
      description: 'Licence required for tables and chairs on public pavement from City of Edinburgh Council.',
      appliesWhen: 'Has outdoor seating',
      frequency: 'Annual',
      penalty: 'Removal of furniture, fine',
      source: 'City of Edinburgh Council',
    },
    {
      id: 'emp-pension',
      title: 'Auto-Enrolment Pensions',
      category: 'employment',
      description: 'Must enrol eligible workers. Minimum contribution: 3% employer, 5% employee. Re-enrolment every 3 years.',
      appliesWhen: 'Has employees (4 employees)',
      frequency: 'Ongoing',
      penalty: 'TPR enforcement: £50-£10,000/day',
      source: 'The Pensions Regulator',
      sourceUrl: 'https://www.thepensionsregulator.gov.uk/en/employers',
    },
    {
      id: 'emp-eli',
      title: "Employer's Liability Insurance",
      category: 'employment',
      description: 'Must hold minimum £5M cover. Display certificate at premises.',
      appliesWhen: 'Has employees',
      frequency: 'Annual renewal',
      penalty: '£2,500 per day without valid insurance',
      source: 'HSE',
      sourceUrl: 'https://www.hse.gov.uk/pubns/hse40.htm',
    },
    {
      id: 'ico-registration',
      title: 'ICO Data Protection Fee',
      category: 'data',
      description: 'Annual data protection fee to Information Commissioner.',
      appliesWhen: 'Handles personal data (customer bookings, staff records)',
      frequency: 'Annual',
      penalty: 'Criminal offence — up to £4,350 fine',
      source: 'ICO',
      sourceUrl: 'https://ico.org.uk/for-organisations/data-protection-fee/',
    },
  ],
  deadlines: [
    {
      id: 'dl-vat-q1',
      title: 'VAT Return — Q1 2026',
      category: 'hmrc',
      dueDate: '2026-05-07',
      description: 'Submit VAT return and payment for Jan-Mar 2026 quarter',
      penalty: '2% surcharge on VAT owed, escalating to 15%',
      action: 'File via HMRC online services',
      severity: 'warning',
    },
    {
      id: 'dl-paye-apr',
      title: 'PAYE RTI — April 2026',
      category: 'hmrc',
      dueDate: '2026-04-05',
      description: 'Report payroll to HMRC on or before payday',
      penalty: '£100-£400/month late filing penalty',
      action: 'Submit via payroll software or HMRC Basic PAYE Tools',
      severity: 'warning',
    },
    {
      id: 'dl-ch-confirmation',
      title: 'Companies House Confirmation Statement',
      category: 'companies_house',
      dueDate: '2026-06-29',
      description: 'Annual confirmation that company details are up to date',
      penalty: '£150 initial penalty, escalating to £1,500',
      action: 'File via Companies House WebFiling',
      severity: 'safe',
    },
    {
      id: 'dl-accounts',
      title: 'Annual Accounts Filing',
      category: 'companies_house',
      dueDate: '2026-12-31',
      description: 'File annual accounts for year ending 31 Mar 2026',
      penalty: '£150 escalating to £1,500',
      action: 'File via Companies House WebFiling',
      severity: 'safe',
    },
    {
      id: 'dl-licence-fee',
      title: 'Premises Licence Annual Fee',
      category: 'scottish',
      dueDate: '2026-08-01',
      description: 'Annual fee to Edinburgh Licensing Board',
      penalty: 'Licence suspension or revocation',
      action: 'Pay annual fee to City of Edinburgh Council Licensing',
      severity: 'safe',
    },
    {
      id: 'dl-corp-tax',
      title: 'Corporation Tax Payment',
      category: 'hmrc',
      dueDate: '2027-01-01',
      description: 'Corporation Tax for year ending 31 Mar 2026',
      penalty: 'Interest + £100 penalty, then £200 after 3 months',
      action: 'Pay via HMRC online',
      severity: 'safe',
    },
    {
      id: 'dl-food-hygiene',
      title: 'Food Hygiene — Maintain Compliance',
      category: 'food_safety',
      dueDate: null,
      description: 'Maintain food hygiene standards. Inspection can happen any time.',
      penalty: 'Closure notice, prosecution, or improvement notice',
      action: "Ensure Safer Food Better Business records are up to date. Allergen info displayed (Natasha's Law).",
      severity: 'warning',
    },
    {
      id: 'dl-ico',
      title: 'ICO Data Protection Fee',
      category: 'data',
      dueDate: '2026-06-15',
      description: 'Annual ICO registration fee (£40 for micro businesses)',
      penalty: 'Criminal offence — up to £4,350 fine',
      action: 'Pay £40 via ICO website',
      severity: 'safe',
    },
  ],
  generatedAt: new Date().toISOString(),
};
